EMB:
  emb_path: '../data/pt_emb'

MTCNN:
  URL: 'http://mtcnn:5000'

triton:
  URL: 'triton:8000'
  model_name: 'facenet'

ELASTICSEARCH:
  URL: 'https://elasticsearch:9200'
  INDEX_NAME: 'wikipedia'
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: changeme