infer:
  img_folder: '../data'

endpt:
  fn_endpt: http://faceid:8000
  yolo_endpt: http://objdet:8000

ELASTICSEARCH:
  URL: 'https://elasticsearch:9200'
  INDEX_NAME: 'documents'
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: changeme