infer:
  img_folder: '../data/images_m2e2'

endpt:
  fn_endpt: http://faceid:8000
  yolo_endpt: http://objdet:8000
  face_server: http://facedb:8000

ELASTICSEARCH:
  URL: 'https://elasticsearch:9200'
  INDEX_NAME: 'documents_m2e2'
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: changeme