version: '3.5'

# To Join any other app setup using another network, change name and set external = true
networks:
  default:
    name: multimodal
    external: true

services:
  jerex-api:
    build: ./
    stdin_open: true
    tty: true
    networks:
      - default
    ports:
      - 8080:8080
    command: ["uvicorn", "api_service:app", "--host", "0.0.0.0", "--port", "8080"]
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    # shm_size: '16gb'
    volumes:
      - .:/jerex
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
