version: '3'
services:
  jerex:
    # image: multimodal-jerex_jerex
    build: ./
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
      - 6006:6006
    networks:
      - backend
    command: "/bin/bash"
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - .:/jerex
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  blink:
    build:
      context: /home/shearman/Desktop/work/BLINK_api
      dockerfile: Dockerfile
    # image: entity_linking
    ports:
      - 5000:5000
    networks:
      - backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - ../BLINK_api/entity_linking_container/models:/blink/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:  
  backend: 
  