version: '3'
services:
  jerex:
    # image: jerex:v0.0.1
    build: ./
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
      - 6006:6006
    command: "/bin/bash"
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - .:/jerex
    ipc: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]