geo_file: '../data/allCountries.txt'
alt_names: '../data/alternateNames.txt'

ELASTICSEARCH:
  URL: 'https://elasticsearch:9200'
  INDEX_NAME: 'geonames'
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: changeme

ARTICLES:
  INDEX_NAME: 'documents_m2e2'

MAPPING:
  mappings:
    properties:
      admin1_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      admin2_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      admin3_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      admin4_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      alternatenames:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      asciiname:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      cc2:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      country_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      dem:
        type: long
      elevation:
        type: float
      feature_class:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      feature_code:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      latitude:
        type: float
      longitude:
        type: float
      modification_date:
        type: date
      name:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
      population:
        type: long
      timezone:
        type: text
        fields:
          keyword:
            type: keyword
            ignore_above: 256
